//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCAssignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriptionrec
    {
        public string customerid { get; set; }
        public string name { get; set; }
        public Nullable<int> amount { get; set; }
        public string status { get; set; }
    }
}
